import { DefaultTheme } from "styled-components/native";

export const theme: DefaultTheme = {
  colors: {
    typeBug: "#8CB230",
    typeDark: "#58575F",
    typeDragon: "#0F6AC0",
    typeEletric: "#EED535",
    typeFairy: "#ED6EC7",
    typeFighting: "#D04164",
    typeFire: "#FD7D24",
    typeFlying: "#748FC9",
    typeGhost: "#556AAE",
    typeGrass: "#62B957",
    typeGround: "#DD7748",
    typeIce: "#61CEC0",
    typeNormal: "#9DA0AA",
    typePoison: "#A552CC",
    typePsychic: "#EA5D60",
    typeRock: "#BAAB82",
    typeSteel: "#417D9A",
    typeWater: "#4A90DA",

    backgroundTypeBug: "#8BD674",
    backgroundTypeDark: "#6F6E78",
    backgroundTypeDragon: "#7383B9",
    backgroundTypeEletric: "#F2CB55",
    backgroundTypeFairy: "#EBA8C3",
    backgroundTypeFighting: "#EB4971",
    backgroundTypeFire: "#FFA756",
    backgroundTypeFlying: "#83A2E3",
    backgroundTypeGhost: "#8571BE",
    backgroundTypeGrass: "#8BBE8A",
    backgroundTypeGround: "#F78551",
    backgroundTypeIce: "#91D8DF",
    backgroundTypeNormal: "#B5B9C4",
    backgroundTypePoison: "#9F6E97",
    backgroundTypePsychic: "#FF6568",
    backgroundTypeRock: "#D4C294",
    backgroundTypeSteel: "#4C91B2",
    backgroundTypeWater: "#58ABF6",

    backgroundWhite: "#FFFFFF",
    backgroundDefaultInput: "#F2F2F2",
    backgroundPressedInput: "#E2E2E2",
    backgroundModal: "#17171780",

    buttonSelected: "#EA5D60",
    buttonUnselected: "#F2F2F2",

    textWhite: "#FFFFFF",
    textBlack: "#17171B",
    textGray: "#747476",
    textNumber: "#17171B99",

    heightShort: "#FFC5E6",
    heightMedium: "#AEBFD7",
    heightTall: "#AAACB8",

    weightLight: "#99CD7C",
    weightNormal: "#57B2DC",
    weightHeavy: "#5A92A5",
  },
  fontSize: {
    sm: 12,
    md: 16,
    lg: 26,
    xxl: 32,
  },
  fontFamily: {
    regular: "SF-Pro-Regular",
    medium: "SF-Pro-Medium",
    bold: "SF-Pro-Bold",
  },
};
